spring.application.name=contacthub

server.port=8081

# mysql database configuration

#data source url
spring.datasource.url=jdbc:mysql://localhost:3306/contacthub

#data source username
spring.datasource.username=root

#data source password
spring.datasource.password=Sidd@Abhi##73

#jpa configuration
spring.jpa.show-sql=true
#for creating schema automatically
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.properties..hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect



# email configuration